THEOS_DEVICE_IP = 192.168.4.96
GO_EASY_ON_ME = 1
export FINALPACKAGE = 0
export THEOS_PACKAGE_SCHEME = rootless

TARGET := iphone:clang:15.5:15.0
INSTALL_TARGET_PROCESSES = SpringBoard

PACKAGE_VERSION = $(THEOS_PACKAGE_BASE_VERSION)
#PACKAGE_VERSION = $(THEOS_PACKAGE_BASE_VERSION)-$(VERSION.INC_BUILD_NUMBER)$(VERSION.EXTRAVERSION)

ARCHS = arm64 arm64e
SDKVERSION = 13.3

TWEAK_NAME = ShutupShortcuts

$(TWEAK_NAME)_FILES = Tweak.x
$(TWEAK_NAME)_CFLAGS = -fobjc-arc
$(TWEAK_NAME)_EXTRA_FRAMEWORKS += Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
SUBPROJECTS += shutupshortcutsprefs
include $(THEOS_MAKE_PATH)/aggregate.mk
